admin_messages/urls.py
from django.urls import path

from admin_messages.views import (
    MessageCreate,
    MessageList,
    MessageView,
    MessageDelete,
    MessageDeleteMany,
    MessageCreateOwner,
)

urlpatterns = [
    path("create/", MessageCreate.as_view(), name="message_create"),
    path(
        "create/owner_id=<owner_id>",
        MessageCreateOwner.as_view(),
        name="message_create_owner",
    ),
    path(
        "create/has_debt=<has_debt>",
        MessageCreate.as_view(),
        name="message_create_has_debt",
    ),
    path("delete/<pk>", MessageDelete.as_view(), name="message_delete"),
    path("delete_many/", MessageDeleteMany.as_view(), name="message_delete_many"),
    path("<pk>", MessageView.as_view(), name="message_view"),
    path("", MessageList.as_view(), name="message_list"),
]

home24/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler403

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("django_admin/", admin.site.urls),
    path("admin/", include("admin_panel.urls")),
    path("cabinet/", include("cabinet.urls")),
    path("", include("website.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "admin_panel.views.error_404"
handler403 = "admin_panel.views.error_403"

users/urls.py
from django.urls import path
from .views import (
    Users,
    CreateUser,
    UpdateUser,
    ViewUser,
    DeleteUser,
    UpdateRoles,
    InviteUser,
)

urlpatterns = [
    path("", Users.as_view(), name="user_list"),
    path("create_user/", CreateUser.as_view(), name="create_user"),
    path("update_user/<pk>/", UpdateUser.as_view(), name="update_user"),
    path("user/<pk>/", ViewUser.as_view(), name="view_user"),
    path("roles/", UpdateRoles.as_view(), name="roles"),
    path("delete_user/<pk>/", DeleteUser.as_view(), name="delete_user"),
    path("invite_user/<pk>/", InviteUser.as_view(), name="invite_user"),
]

admin_messages/models.py
from admin_apartment.models import Apartment
from admin_house.models import House, Floor, Section
from users.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="sender"
    )
    receivers = models.ManyToManyField(User)
    house = models.ForeignKey(House, on_delete=models.CASCADE, null=True)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE, null=True)
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=78)
    text = models.TextField()
    is_read = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)

    @property
    def get_receiver_label(self):
        if (
            not (self.house or self.section or self.apartment or self.floor)
            and self.receivers.count() == 1
        ):
            return str(self.receivers.first())
        if self.house:
            return (
                f'{self.house} {self.section or ""} '
                f'{self.floor or ""} {self.apartment or ""}'
            )
        else:
            return "Всім"

admin_messages/forms.py
from django import forms
from admin_apartment.models import Apartment
from admin_house.models import Section, House, Floor
from admin_messages.models import Message
from users.models import User


class MessageForm(forms.ModelForm):
    subject = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Тема повідомлення:"}
        )
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "compose-textarea form-control",
                "rows": "5",
                "placeholder": "Текст повідомлення:",
            }
        ),
        required=False,
    )
    house = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control select2-field"}),
        empty_label="",
        queryset=House.objects.all(),
        required=False,
    )
    section = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control select2-field"}),
        empty_label="",
        queryset=Section.objects.all(),
        required=False,
    )
    floor = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control select2-field"}),
        empty_label="",
        queryset=Floor.objects.all(),
        required=False,
    )
    apartment = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control select2-field"}),
        empty_label="",
        required=False,
        queryset=Apartment.objects.all(),
    )
    owners_has_debt = forms.BooleanField(widget=forms.CheckboxInput(), required=False)

    receiver = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control select2-field"}),
        empty_label="",
        queryset=User.get_owners(),
        required=False,
    )

    class Meta:
        model = Message
        fields = "__all__"
        exclude = ["receivers", "sender", "owners_has_debt", "receiver"]

admin_messages/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, DeleteView

from admin_apartment.models import Apartment
from admin_house.models import Section, Floor
from admin_messages.forms import MessageForm
from admin_personal_account.models import PersonalAccount
from users.models import User
from users.mixins import AdminPermissionRequiredMixin
from admin_messages.models import Message


# Create your views here.
class MessageCreate(AdminPermissionRequiredMixin, CreateView):
    permission_required = "messages"
    model = Message
    form_class = MessageForm
    template_name = "admin_messages/admin_messages_create.html"
    success_url = reverse_lazy("message_list")

    def get_form_kwargs(self):
        if self.kwargs.get("has_debt"):
            self.initial = {"owners_has_debt": True}
        return super(MessageCreate, self).get_form_kwargs()

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            result = {}
            house_id = self.request.GET.get("house_id")
            section_id = self.request.GET.get("section_id")
            floor_id = self.request.GET.get("floor_id")
            print(self.request.GET)
            apartment_filters = {}
            if house_id:
                apartment_filters["house"] = house_id
                if floor_id:
                    apartment_filters["floor"] = floor_id
                else:
                    result["floors"] = list(
                        Floor.objects.filter(house=house_id).values("id", "name")
                    )
                if section_id:
                    apartment_filters["section"] = section_id
                else:
                    result["sections"] = list(
                        Section.objects.filter(house=house_id).values("id", "name")
                    )
                result["apartments"] = list(
                    Apartment.objects.filter(**apartment_filters).values("id", "number")
                )
            return JsonResponse(result, safe=False, **response_kwargs)
        else:
            return super(CreateView, self).render_to_response(
                context, **response_kwargs
            )

    def form_valid(self, form):
        form = form.save(commit=False)
        form.sender = self.request.user
        form.save()
        owner_filters = {
            "apartment__house": form.house,
            "apartment__section": form.section,
            "apartment__floor": form.floor,
            "apartment": form.apartment,
        }
        owner_filters = {k: v for k, v in owner_filters.items() if v}
        owners = User.get_owners().filter(**owner_filters)
        if self.request.POST.get("owners_has_debt"):
            owner_list = []
            for owner in owners:
                if owner not in owner_list:
                    if PersonalAccount.owner_has_debt(owner_id=owner.id):
                        owner_list.append(owner)
            form.receivers.add(*owner_list)
        else:
            form.receivers.add(*owners)
        self.object = form
        messages.success(self.request, "Повідомлення успішно створено")
        return HttpResponseRedirect(self.get_success_url())


class MessageCreateOwner(MessageCreate):
    template_name = "admin_messages/admin_message_create_user.html"

    def get_form_kwargs(self):
        if self.kwargs.get("owner_id"):
            self.initial = {"receiver": self.kwargs.get("owner_id")}
        return super(MessageCreateOwner, self).get_form_kwargs()

    def form_valid(self, form):
        form = form.save(commit=False)
        form.sender = self.request.user
        form.save()
        if self.request.POST.get("receiver"):
            form.receivers.add(self.request.POST.get("receiver"))
        messages.success(self.request, "Повідомлення успішно створено")
        return HttpResponseRedirect(self.success_url)


class MessageList(AdminPermissionRequiredMixin, ListView):
    permission_required = "messages"
    model = Message
    template_name = "admin_messages/admin_messages_list.html"
    ordering = "-created"

    def get_queryset(self):
        return (
            Message.objects.select_related("house", "section", "floor", "apartment")
            .prefetch_related("receivers")
            .order_by(self.ordering)
        )

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            search_value = self.request.GET.get("search[value]")
            filtered_qs = self.get_queryset().filter(
                Q(text__contains=search_value) | Q(subject__contains=search_value)
            )
            result_list = list(filtered_qs.values("id", "text", "subject", "created"))
            for message in result_list:
                message["receivers"] = filtered_qs.get(
                    id=message["id"]
                ).get_receiver_label
            start = int(self.request.GET.get("start", 0))
            length = int(self.request.GET.get("length", 10))
            paginator = Paginator(result_list, self.request.GET.get("length", 10))
            page = (start // length) + 1
            data = list(paginator.get_page(page))
            result = {
                "data": data,
                "recordsTotal": paginator.count,
                "recordsFiltered": paginator.count,
                "pages": paginator.num_pages,
            }
            return JsonResponse(result, safe=False, **response_kwargs)
        else:
            return super(ListView, self).render_to_response(context, **response_kwargs)


class MessageView(AdminPermissionRequiredMixin, DetailView):
    permission_required = "messages"
    model = Message
    template_name = "admin_messages/admin_messages_view.html"


class MessageDelete(AdminPermissionRequiredMixin, DeleteView):
    permission_required = "messages"
    model = Message
    success_message = "Повідомлення видалено успішно"
    success_url = reverse_lazy("message_list")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class MessageDeleteMany(AdminPermissionRequiredMixin, View):
    permission_required = "messages"

    def delete(self, request, *args, **kwargs):
        object_list = self.request.POST.getlist("selected_messages[]")
        for obj_pk in object_list:
            Message.objects.get(pk=obj_pk).delete()
        messages.success(self.request, "Повідомлення видалено успішно")
        return HttpResponse("Success")

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

admin_messages/templates/admin_messages/admin_message_create_user.html
{% extends 'admin_messages/admin_messages_create.html' %}
{% block user_create %}
    <div class="form-group field-{{ form.receiver.id_for_label }}">
        <label class="control-label" for="{{ form.receiver.id_for_label }}">Власник квартир</label>
        {{form.receiver}}
        <div class="help-block"></div>
    </div>
{% endblock %}
{% block user_create_scripts %} {% endblock %}

admin_messages/templates/admin_messages/admin_messages_create.html
{% extends 'layout/admin_panel.html' %}
{% load static %}
{% block head %}
    <style>
    .ck-editor__editable {
        min-height: 200px;
    }
    </style>
{% endblock %}
{% block title %}Нове повідомлення{% endblock %}
{% block breadcrumb %}
    <ul class="breadcrumb">
        <li><a href="{% url 'statistic' %}"><i class="fa fa-home"></i>Головна</a></li>
        <li><a href="{% url 'message_list' %}">Повідомлення</a></li>
        <li class="active">Нове повідомлення</li>
    </ul>
{% endblock %}
{% block header_text %}
    нове повідомлення
{% endblock %}
{% block content %}
    <div class="box">

        <form id="message_form" method="post">
            {% csrf_token %}
            <div class="box-header with-border">
                <h3 class="box-title"></h3>
            </div>
            <div class="box-body">
                <div class="form-group field-{{ form.subject.id_for_label }}">

                    {{form.subject}}

                    <div class="help-block"></div>
                </div>
                <div class="form-group field-{{ form.text.id_for_label }}">
                    {{form.text}}
                </div>

                <div class="row">

                    <div class="col-xs-12 col-md-6">
                        <h4>Кому відправити:</h4>

                        {% block user_create %}
                        <div class="form-group field-{{ form.owners_has_debt.id_for_label }}">

                            <label>{{form.owners_has_debt}} Власникам із заборгованостями</label>

                            <div class="help-block"></div>
                        </div>
                        <div class="form-group field-{{ form.house.id_for_label }} ">
                            <label class="control-label" for="{{form.house.id_for_label }}">ЖК</label>
                            {{form.house}}

                            <div class="help-block"></div>
                        </div>
                        <div class="form-group field-{{ form.apartment.id_for_label }} ">
                            <label class="control-label" for="{{ form.section.id_for_label }}">Секція</label>
                            {{form.section}}

                            <div class="help-block"></div>
                        </div>
                        <div class="form-group field-{{ form.apartment.id_for_label }} ">
                            <label class="control-label" for="{{ form.floor.id_for_label }}">Поверх</label>
                            {{form.floor}}


                            <div class="help-block"></div>
                        </div>
                        <div class="form-group field-{{ form.apartment.id_for_label }} ">
                            <label class="control-label" for="{{ form.apartment.id_for_label }}">Квартира</label>
                            {{form.apartment}}

                            <div class="help-block"></div>
                        </div>
                        {{form.apartment.id}}
                         {% endblock %}
                    </div>
                </div>

            </div>
            <div class="box-footer">
                <div class="pull-right">
                    <button type="submit" class="btn btn-success"><i class="fa fa-envelope-o"></i> Надіслати</button>
                </div>
            </div>
            {{form.errors}}
        </form>
    </div>

{% endblock %}
{% block scripts %}
    <script>
    $('#nav_message').attr('class', 'active')
    </script>
        <script src="{% static 'admin_panel/bower_components/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/select2/dist/js/i18n/uk.js' %}"></script>
        <script type="text/javascript" src="{% static "admin_panel/plugins/ckeditor5-build-classic/ckeditor.js" %}"></script>
    <script type="text/javascript" src="{% static "admin_panel/plugins/ckeditor5-build-classic/translations/ru.js" %}"></script>
    <script>
    $('.select2-field').select2({placeholder: "Всім...",allowClear:true})
    </script>
    <script>
    $(document).ready(
            ClassicEditor.create( document.querySelector( '#id_text' ),{
            language: 'ru',
        toolbar:{
        items: [
'heading',
'|',
'bold',
'italic',
'underline',
'link',
'bulletedList',
'numberedList',
'|',
'outdent',
'indent',
'|',
'blockQuote',
'undo',
'redo'
]
        }
        } )
        .catch (error => {
            console.error(error);
        } )
    )

    </script>
    {% block user_create_scripts %}
    <script>
        let select_options = {}

        function clear_options(target_id) {
            $('#' + `${target_id} option:not([value=''])`).remove()
        }

        function get_values(values) {
            $.ajax({
                type: 'GET',
                url: '{% url 'message_create' %}',
                data: select_options,
                success: function (data) {
                    console.log(data)
                    console.log(select_options)
                    if (data['sections']) {
                        clear_options('id_apartment')
                        clear_options('id_section')
                        data['sections'].forEach(
                            function (item) {
                                $('#id_section').append($('<option>').val(item['id']).text(item['name']));
                            }
                        );
                    }
                    if (data['floors']) {
                        clear_options('id_apartment')
                        clear_options('id_floor')
                        data['floors'].forEach(
                            function (item) {
                                $('#id_floor').append($('<option>').val(item['id']).text(item['name']));
                            }
                        );
                    }
                    if (data['apartments']) {
                        clear_options('id_apartment')
                        data['apartments'].forEach(
                            function (item) {
                                $('#id_apartment').append($('<option>').val(item['id']).text(item['number']));
                            });
                    }
                }
            })
        }

        function set_event_listeners(house = false, section = false, floor = false, apartment = false) {
            if (house) {
                $('#id_house').change(function() {
                    select_options['house_id'] = this.value
                    select_options['section_id'] = ''
                    select_options['floor_id'] = ''
                    select_options['apartment_id'] = ''
                    get_values()
                })
            }
            if (section) {
                $('#id_section').change(function() {
                    select_options['section_id'] = this.value
                    select_options['apartment_id'] = ''
                    get_values()
                })
            }
            if (floor) {
                $('#id_floor').change(function() {
                    select_options['floor_id'] = this.value
                    select_options['apartment_id'] = ''
                    get_values()
                })
            }
        }

        $(document).ready(function() {
                clear_options('id_apartment')
                clear_options('id_section')
                clear_options('id_floor')
                set_event_listeners(true, true, true, true);


            }
        )
    </script>
    {% endblock %}
    <script>
            $( "#message_form" ).validate( {
rules: {
subject: "required",
text: "required",
},
messages: {
subject: "Введіть тему повідомлення.",
text: "Будь ласка, введіть текст повідомлення.",
},
errorElement: "em",
errorPlacement: function ( error, element ) {
error.addClass( "help-block");
element.parents( ".form-group" ).addClass( "has-feedback" );
if ( element.prop( "type" ) === "checkbox" ) {
error.insertAfter( element.parent( "label" ) );
} else {
                        if($(element).hasClass('select2-hidden-accessible')){

                            error.insertAfter( $(element).parent('.form-group').find('.select2'));
                        }
                        else error.insertAfter( element );
}
},
success: function ( label, element ) {
},
highlight: function ( element, errorClass, validClass ) {
$( element ).parents( ".form-group" ).addClass( "has-error" ).removeClass( "has-success" );
},
unhighlight: function ( element, errorClass, validClass ) {
$( element ).parents( ".form-group" ).addClass( "has-success" ).removeClass( "has-error" );
}
} );
             $("select").on("select2:close", function (e) {
        $(this).valid();
    });
    </script>
{% endblock %}

admin_messages/templates/admin_messages/admin_messages_list.html
{% extends 'layout/admin_panel.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'admin_panel/plugins/iCheck/flat/blue.css' %}" rel="stylesheet">
{% endblock %}
{% block title %} Повідомлення {% endblock %}
{% block breadcrumb %}
    <ul class="breadcrumb">
        <li><a href="{% url 'statistic' %}"><i class="fa fa-home"></i>Головна</a></li>
        <li class="active">Повідомлення</li>
    </ul>
{% endblock %}
{% block header_text %}
    Повідомлення
{% endblock %}
{% block content %}


    <div class="row">
        <!--<div class="col-xs-12 col-sm-6">-->
        <!--<h2 class="page-header">Власники квартир</h2>-->
        <!--</div>-->
        <div class="col-xs-12">

            <div class="pull-right margin-bottom">
                <a class="btn btn-success" href="{% url 'message_create' %}">Надіслати повідомлення</a>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"></h3>

            <div class="box-tools pull-right">
                <div class="has-feedback">
                    <form action="" method="get">

                        <input id="search" type="text" name="search" class="form-control input-sm" placeholder="Пошук">
                        <span class="glyphicon glyphicon-search form-control-feedback"></span>
                    </form>
                </div>
            </div>
        </div>
        <div class="box-body no-padding">

            <div id="w0" class="grid-view">
                <div class="mailbox-controls">
                    <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i>
                    </button>
                    <button id="delete_many" type="button" class="btn btn-default btn-sm delete-many"><i
                            class="fa fa-trash-o"></i>
                    </button>

                    <div class="pull-right">
                        <ul class="pagination pagination-sm no-margin pull-right"></ul>
                    </div>
                </div>

                <div class="mailbox-messages">
                    <table id="messages_table" class="table table-bordered table-hover table-striped linkedRow">
                        <thead>
                        <tr>
                            <th> </th>
                            <th style="min-width: 200px">Одержувачі</th>
                            <th>Текст</th>
                            <th style="width: 135px; min-width: 135px">Дата</th>
                        </tr>
                        </thead>
                        <tbody>
                        {# {% for message in message_list %}#}
                        {# {% url 'message_view' message.pk as message_url%}#}
                        {# <tr data-href="{{message_url}}">#}
                        {# <td>#}
                        {# <input type="checkbox" name="selection[]" value="{{ message.pk }}"#}
                        {# style="position: absolute; opacity: 0;">#}
                        {#</td>#}
                        {# <td><a href="{{message_url}}">{{ message.get_receiver_label }}</a>#}
                        {#</td>#}
                        {# <td><strong>{{ message.subject }}</strong> - {{ message.text|striptags }}</td>#}
                        {# <td>{{ message.created|date:'d.m.Y - H:m' }}</td>#}
                        {#</tr>#}
                        {# {% endfor %}#}
                        </tbody>
                    </table>
                </div>

                <div class="mailbox-controls">
                    <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i>
                    </button>
                    <button type="button" class="btn btn-default btn-sm delete-many"><i class="fa fa-trash-o"></i>
                    </button>
                    <div class="pull-right">
                        <ul class="pagination pagination-sm no-margin pull-right"></ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <form>{% csrf_token %}</form>
{% endblock %}
{% block scripts %}
    <script src="{% static 'admin_panel/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/moment/moment.js' %}"></script>
    <script>
        $('#nav_message').attr('class', 'active')
    </script>
    <script src="{% static 'admin_panel/plugins/iCheck/icheck.min.js' %}"></script>
    <script>
    let selected_messages = []
    let table
        function send_POST(e) {
            table = $('#messages_table').DataTable({

                serverSide: true,
                autoWidth: false,
                processing: true,

                oLanguage: {
                    sZeroRecords: "Нічого не знайдено."
                },
                columnDefs: [
                    {targets: '_all', defaultContent: '', className: "message"},
                ],
                "ajax": {
                    "processing": true,
                    "url": "{% url 'message_list' %}",
                    "data": function (d) {
                        return d;
                    },
                },
                "columns": [
                    {
                        "data": "id",
                        render: function (data) {
                            return `<input type="checkbox" name="selection[]" value="${data}"
                                style="position: absolute; opacity: 0;">`

                        }
                    },
                    {"data": "receivers"},
                    {
                        "data": "text",
                        render: function (data, type, row) {
                            return `<strong>${$(data).text()}</strong> - ${row.subject}`
                        }
                    },
                    {
                        "data": "created",
                        render: function (data) {
                            return moment.utc(data).format('DD.MM.YYYY')
                        }
                    }
                ],
                paging: true,
                'lengthChange': false,
                'pageLength': 10,
                searching: true,
                dom: 'lrtp',
                ordering: false,
                info: false,
                drawCallback: function (settings) {
                    let checkboxes = $('.mailbox-messages input[type="checkbox"]')
                    checkboxes.iCheck({
                        checkboxClass: 'icheckbox_flat-blue',
                        radioClass: 'iradio_flat-blue'
                    });
                    selected_messages = []
                    checkboxes.iCheck({
                        checkboxClass: 'icheckbox_flat-blue',
                        radioClass: 'iradio_flat-blue'
                    });
                    checkboxes.on('ifChecked', function() {
                        selected_messages.push(this.value)
                    });
                    checkboxes.on('ifUnchecked', function() {
                        let index = selected_messages.indexOf(this.value);
                        if (index > -1) {
                            selected_messages.splice(index, 1);
                        }
                    });
                },
                initComplete: (settings, json) => {
                    $('.dataTables_paginate').appendTo('.pagination-sm');
                },
            });
            $('#search').keyup(function() {
                table.search($(this).val()).draw();
            })
        }

        $(document).ready(function() {
            send_POST()
            table.on('click', 'tbody tr .message', function() {
                window.location.href = '{% url 'message_view' 12345 %}'.replace(/12345/, table.row(this).data().id)
            })
            //Enable check and uncheck all functionality
            $(".checkbox-toggle").click(function() {
                let clicks = $(this).data('clicks');
                if (clicks) {
                    //Uncheck all checkboxes
                    $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
                    $(".checkbox-toggle > .fa").removeClass("fa-check-square-o").addClass('fa-square-o');
                } else {
                    //Check all checkboxes
                    $(".mailbox-messages input[type='checkbox']").iCheck("check");
                    $(".checkbox-toggle > .fa").removeClass("fa-square-o").addClass('fa-check-square-o');
                }
                $(this).data("clicks", !clicks);
            });
        })
    </script>
    <script>
        $('#delete_many').click(function() {
            alertify.confirm('Підтвердження видалення', 'Видалити вибрані повідомлення?',
                function () {
                    $.ajax({
                        type: 'POST',
                        url: '{% url 'message_delete_many' %}',
                        data: {'selected_messages': selected_messages},
                        headers: {
                            "X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val()
                        },
                        success: function (data) {
                            location.reload();
                        }
                    })
                },
                function () {
                }).set({labels: {ok: 'Підтвердити', cancel: 'Скасувати'}});
        })
    </script>
{% endblock %}