admin_house/urls.py
from django.urls import path, include
from .views import HouseCreate, HouseList, HouseUpdate, HouseView, house_delete

urlpatterns = [
    path("create/", HouseCreate.as_view(), name="house_create"),
    path("update/<pk>", HouseUpdate.as_view(), name="house_update"),
    path("<pk>", HouseView.as_view(), name="house_view"),
    path("delete/<pk>", house_delete, name="house_delete"),
    path("", HouseList.as_view(), name="house_list"),
]

home24/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler403

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("django_admin/", admin.site.urls),
    path("admin/", include("admin_panel.urls")),
    path("cabinet/", include("cabinet.urls")),
    path("", include("website.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "admin_panel.views.error_404"
handler403 = "admin_panel.views.error_403"

users/urls.py
from django.urls import path
from .views import (
    Users,
    CreateUser,
    UpdateUser,
    ViewUser,
    DeleteUser,
    UpdateRoles,
    InviteUser,
)

urlpatterns = [
    path("", Users.as_view(), name="user_list"),
    path("create_user/", CreateUser.as_view(), name="create_user"),
    path("update_user/<pk>/", UpdateUser.as_view(), name="update_user"),
    path("user/<pk>/", ViewUser.as_view(), name="view_user"),
    path("roles/", UpdateRoles.as_view(), name="roles"),
    path("delete_user/<pk>/", DeleteUser.as_view(), name="delete_user"),
    path("invite_user/<pk>/", InviteUser.as_view(), name="invite_user"),
]

admin_house/models.py
from django.db import models
from users.models import User


# Create your models here.
class House(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        error_messages={"unique": "Будинок із такою назвою вже існує!"},
    )
    address = models.CharField(
        max_length=50,
        unique=True,
        error_messages={"unique": "Будинок із такою адресою вже існує!"},
    )
    image1 = models.ImageField(upload_to="houses")
    image2 = models.ImageField(upload_to="houses")
    image3 = models.ImageField(upload_to="houses")
    image4 = models.ImageField(upload_to="houses")
    image5 = models.ImageField(upload_to="houses")
    users = models.ManyToManyField(User, through="HouseUser")
    date_edit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-date_edit"]


class Section(models.Model):
    name = models.CharField(max_length=50)
    house = models.ForeignKey(House, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Floor(models.Model):
    name = models.CharField(max_length=50)
    house = models.ForeignKey(House, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class HouseUser(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

admin_house/forms.py
from django import forms
from django.forms import modelformset_factory
from PIL import Image
from .models import House, Section, Floor, HouseUser
from users.models import User, Role


class RoleModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.role.role


class HouseForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    address = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    def __init__(self, *args, **kwargs):
        super(HouseForm, self).__init__(*args, **kwargs)
        self.fields["image1"].required = False
        self.fields["image1"].widget = forms.FileInput(attrs={"accept": "image/*"})
        self.fields["image2"].required = False
        self.fields["image2"].widget = forms.FileInput(attrs={"accept": "image/*"})
        self.fields["image3"].required = False
        self.fields["image3"].widget = forms.FileInput(attrs={"accept": "image/*"})
        self.fields["image4"].required = False
        self.fields["image4"].widget = forms.FileInput(attrs={"accept": "image/*"})
        self.fields["image5"].required = False
        self.fields["image5"].widget = forms.FileInput(attrs={"accept": "image/*"})

    class Meta:
        model = House
        fields = "__all__"
        exclude = ["users"]


class SectionForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    def __init__(self, *args, **kwargs):
        super(SectionForm, self).__init__(*args, **kwargs)
        self.fields["house"].required = False

    class Meta:
        model = Section
        fields = "__all__"


SectionFormSet = modelformset_factory(
    model=Section, form=SectionForm, extra=0, can_delete=True
)


class FloorForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    def __init__(self, *args, **kwargs):
        super(FloorForm, self).__init__(*args, **kwargs)
        self.fields["house"].required = False

    class Meta:
        model = Floor
        fields = "__all__"


FloorFormSet = modelformset_factory(
    model=Floor, form=FloorForm, extra=0, can_delete=True
)


class HouseUserForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control"}),
        queryset=User.objects.exclude(role__role=Role.RoleName.OWNER),
        required=True,
    )
    role = RoleModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control", "disabled": ""}),
        queryset=User.objects.exclude(role__role=Role.RoleName.OWNER),
        required=False,
    )

    class Meta:
        model = HouseUser
        fields = [
            "user",
        ]
        exclude = ["role"]


HouseUserFormSet = modelformset_factory(
    model=HouseUser, form=HouseUserForm, extra=0, can_delete=True
)

admin_house/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.contrib import messages

from users.mixins import AdminPermissionRequiredMixin
from .forms import HouseForm, SectionFormSet, FloorFormSet, HouseUserFormSet
from .models import House, Section, Floor, HouseUser


# Create your views here.
class HouseList(AdminPermissionRequiredMixin, ListView):
    permission_required = "applications"
    model = House
    template_name = "admin_house/house_list.html"

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            filtered_qs = self.get_queryset()
            print(self.request.GET)
            filter_fields = {
                "name__contains": self.request.GET.get("name"),
                "address__contains": self.request.GET.get("address"),
            }
            filter_fields = {k: v for k, v in filter_fields.items() if v}
            filtered_qs = filtered_qs.filter(**filter_fields)
            if self.request.GET.get("order_by"):
                filtered_qs = filtered_qs.order_by(self.request.GET.get("order_by"))

            filtered_qs = filtered_qs.values("id", "name", "address")
            start = int(self.request.GET.get("start", 0))
            length = int(self.request.GET.get("length", 10))
            paginator = Paginator(filtered_qs, self.request.GET.get("length", 10))
            page = (start // length) + 1
            data = list(paginator.get_page(page))
            result = {
                "data": data,
                "recordsTotal": paginator.count,
                "recordsFiltered": paginator.count,
                "pages": paginator.num_pages,
            }
            print(result)
            return JsonResponse(result, safe=False, **response_kwargs)
        else:
            return super(ListView, self).render_to_response(context, **response_kwargs)


class HouseView(AdminPermissionRequiredMixin, DetailView):
    permission_required = "houses"
    model = House
    template_name = "admin_house/house_view.html"


def house_delete(request, pk):
    obj_house = House.objects.get(pk=pk)
    messages.success(request, f"Будинок {obj_house.name} успішно видалено")
    obj_house.delete()
    return redirect("house_list")


class HouseCreate(AdminPermissionRequiredMixin, CreateView):
    permission_required = "houses"
    model = House
    template_name = "admin_house/house_create.html"
    form_class = HouseForm
    success_url = "house_list"

    def get_context_data(self, **kwargs):
        context = super(HouseCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context["section_formset"] = SectionFormSet(
                self.request.POST, prefix="section"
            )
            context["floor_formset"] = FloorFormSet(self.request.POST, prefix="floor")
            context["house_user_formset"] = HouseUserFormSet(
                self.request.POST, prefix="house_user"
            )
        else:
            context["section_formset"] = SectionFormSet(
                prefix="section", queryset=Section.objects.none()
            )
            context["floor_formset"] = FloorFormSet(
                prefix="floor", queryset=Floor.objects.none()
            )
            context["house_user_formset"] = HouseUserFormSet(
                prefix="house_user", queryset=HouseUser.objects.none()
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        context = self.get_context_data()
        floor_formset = context["floor_formset"]
        section_formset = context["section_formset"]
        house_user_formset = context["house_user_formset"]
        if (
            floor_formset.is_valid()
            and section_formset.is_valid()
            and form.is_valid()
            and house_user_formset.is_valid()
        ):
            return self.form_valid(
                form, floor_formset, section_formset, house_user_formset
            )
        else:
            return super(HouseCreate, self).render_to_response(self.get_context_data())

    def form_valid(self, form, floor_formset, section_formset, house_user_formset):
        house = form.save()
        floors = floor_formset.save(commit=False)
        sections = section_formset.save(commit=False)
        house_users = house_user_formset.save(commit=False)
        for floor in floors:
            floor.house_id = house.pk
        for section in sections:
            section.house_id = house.pk
        for house_user in house_users:
            house_user.house_id = house.pk
        floor_formset.save()
        section_formset.save()
        house_user_formset.save()
        messages.success(self.request, f"Будинок {house.name} сворено успішно")
        return redirect(self.success_url)


class HouseUpdate(AdminPermissionRequiredMixin, UpdateView):
    permission_required = "houses"
    model = House
    form_class = HouseForm
    template_name = "admin_house/house_update.html"
    success_url = "house_list"

    def get_context_data(self, **kwargs):
        context = super(HouseUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context["section_formset"] = SectionFormSet(
                self.request.POST, prefix="section"
            )
            context["floor_formset"] = FloorFormSet(self.request.POST, prefix="floor")
            context["house_user_formset"] = HouseUserFormSet(
                self.request.POST, prefix="house_user"
            )
        else:
            context["section_formset"] = SectionFormSet(
                prefix="section",
                queryset=Section.objects.filter(house=self.kwargs["pk"]),
            )
            context["floor_formset"] = FloorFormSet(
                prefix="floor", queryset=Floor.objects.filter(house=self.kwargs["pk"])
            )
            context["house_user_formset"] = HouseUserFormSet(
                prefix="house_user",
                queryset=HouseUser.objects.filter(house=self.kwargs["pk"]),
            )
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        context = self.get_context_data()
        floor_formset = context["floor_formset"]
        section_formset = context["section_formset"]
        house_user_formset = context["house_user_formset"]
        if (
            floor_formset.is_valid()
            and section_formset.is_valid()
            and form.is_valid()
            and house_user_formset.is_valid()
        ):
            return self.form_valid(
                form, floor_formset, section_formset, house_user_formset
            )
        else:
            return super(HouseUpdate, self).render_to_response(self.get_context_data())

    def form_valid(self, form, floor_formset, section_formset, house_user_formset):
        house = form.save()
        floors = floor_formset.save(commit=False)
        sections = section_formset.save(commit=False)
        house_users = house_user_formset.save(commit=False)
        for floor in floors:
            floor.house_id = house.pk
        for section in sections:
            section.house_id = house.pk
        for house_user in house_users:
            house_user.house_id = house.pk
        floor_formset.save()
        section_formset.save()
        house_user_formset.save()
        messages.success(self.request, f"Будинок {house.name} успішно обновлено")
        return redirect(self.success_url)

admin_house/templates/admin_house/house_list.html
{% extends 'layout/admin_panel.html' %}
{% load static %}
{% block title %}Будинки{% endblock %}
{% block header_text %}
    Будинки
{% endblock %}
{% block breadcrumb %}
    <ul class="breadcrumb">
        <li><a href="{% url 'statistic' %}"><i class="fa fa-home"></i>Головна</a></li>
        <li class="active">Будинки</li>
    </ul>
{% endblock %}
{% block content %}


    <div class="row">
        <div class="col-xs-12">
            <div class="pull-right margin-bottom">
                <a class="btn btn-success" href="{% url 'house_create' %}">Додати будинок</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools">
                        <button onclick="clear_filters()" class="btn btn-default btn-sm">
                            <span class="hidden-xs">Очистити</span><i class="fa fa-eraser visible-xs"
                                                                      aria-hidden="true"></i>
                        </button>
                    </div>
                </div>

                <div id="w0" class="grid-view">
                    <div class="box-body table-responsive no-padding">
                        <table id="house_table" class="table table-bordered table-hover table-striped linkedRow">
                            <thead>
                            <tr>
                                <th style="width: 40px; min-width: 40px">#</th>
                                <th><a id="name" class="ordering" style="cursor: pointer">Назва</a></th>
                                <th><a id="address" class="ordering" style="cursor: pointer">Адреса</a></th>
                                <th style="width: 80px; min-width: 80px"> </th>
                            </tr>
                            <tr id="w0-filters" class="filters">
                                <td> </td>
                                <td><input id="name" type="text" class="form-control column_search"
                                           name="HouseNameSearch"></td>
                                <td><input id="address" type="text" class="form-control column_search"
                                           name="HouseAddressSearch"></td>
                                <td> </td>
                            </tr>
                            </thead>
                            <tbody>
                            {#{% for house in house_list %}#}
                            {#<tr data-href="/admin/house/191" data-key="{{ house.pk }}">#}
                            {# <td>{{ forloop.counter }}</td>#}
                            {# <td>{{ house.name }}</td>#}
                            {# <td>{{ house.address }}</td>#}
                            {# <td>#}
                            {# <div class="btn-group pull-right">#}
                            {# <a class="btn btn-default btn-sm" href="/admin/house/update/191"#}
                            {# title="Редагувати" data-toggle="tooltip">#}
                            {# <i class="fa fa-pencil"></i>#}
                            {#</a>#}
                            {# <a class="btn btn-default btn-sm" href="/admin/house/delete/191"#}
                            {# title="Видалити" data-toggle="tooltip" data-pjax="0" data-method="post"#}
                            {# data-confirm="Ви впевнені, що хочете видалити цей елемент?">#}
                            {# <i class="fa fa-trash"></i>#}
                            {#</a>#}
                            {#</div>#}
                            {#</td>#}
                            {#</tr>#}
                            {#{% endfor %}#}
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer clearfix"></div>
                </div>
                <div class="box-footer">
                    <div>Кількість будинків: <span class="text-bold">{{house_list.count}}</span></div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $('#nav_house').attr('class', 'active')
    </script>
    <script src="{% static 'admin_panel/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'admin_panel/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

    <script>
        let numb = 0
        let sort_data = {
            "name": '',
            "address": '',
            "order_by": ''
        }
        let order_by = ''
        let table

        function clear_filters() {
            $('.column_search').val('');
            $('.ordering').attr('class', 'ordering');
            sort_data = {
                "name": '',
                "address": '',
                "order_by": ''
            }
            numb = 0
            table.draw()

        }

        function send_POST(e) {
            table = $('#house_table').DataTable({
                serverSide: true,
                processing: false,
                ordering: false,
                oLanguage: {
                    sZeroRecords: "Нічого не знайдено."
                },
                columnDefs: [
                    {className: "house", "targets": [0, 1, 2]},
                    {targets: '_all', defaultContent: ''},
                ],
                "ajax": {
                    "processing": true,
                    "url": "{% url 'house_list' %}",
                    "data": function (d) {
                        numb = d['start']
                        return Object.assign(d, sort_data);
                    },
                },
                "columns": [
                    {
                        data: null,
                        render: function () {
                            numb++
                            return numb
                        }
                    },
                    {data: 'name'},
                    {data: 'address'},
                    {
                        data: 'id',
                        render: function (data, type) {
                            let link_update = '{% url 'house_update' 12345 %}'.replace(/12345/, data)
                            let link_delete = '{% url 'house_delete' 12345 %}'.replace(/12345/, data)
                            return `<div class="btn-group pull-right">\
            <a class="btn btn-default btn-sm" href="${link_update}"\
               title="Редагувати" data-toggle="tooltip">\
                <i class="fa fa-pencil"></i>\
            </a>\
            <a class="btn btn-default btn-sm"\
               title="Видалити" data-toggle="tooltip" data-pjax="0" data-method="post"\
                onclick="return confirm_delete('${link_delete}',event);">\
                <i class="fa fa-trash"></i>\
            </a>\
        </div>`
                        },
                    },
                ],
                paging: true,
                'pageLength': 10,
                'lengthChange': false,
                initComplete: (settings, json) => {
                    $('.dataTables_paginate').appendTo('.pagination-sm');
                },
                searching: false,
                info: false,
            });
        }

        let table_head = $('#house_table thead')
        table_head.on('keyup', ".column_search", function a(e) {
            sort_data[this.id] = $(this).val()
            {#numb = 0#}
            table.draw()
        });

        table_head.on('click', '.ordering', function() {
            if (this.className === 'ordering asc') {
                $(this).attr('class', 'ordering desc')
                sort_data['order_by'] = '-' + this.id
            } else {
                $(this).attr('class', 'ordering asc')
                sort_data['order_by'] = this.id
            }
            table_head.find('.ordering').not(this).attr('class', 'ordering')
            {#numb = 0#}
            table.draw()
        })

        function confirm_delete(link, event) {
            alertify.confirm('Підтвердження видалення', 'Видалити будинок <b>'
                + $(event.target).closest("tr ").children().eq(1).text() + '</b> ?',
                function () {
                    window.location.href = link
                },
                function () {
                }).set({labels: {ok: 'Підтвердити', cancel: 'Скасувати'}});
            return false;
        }

        $('#house_table').on('click', 'tbody tr .house', function () {
            window.location.href = '{% url 'house_view' 12345 %}'.replace(/12345/, table.row(this).data().id)
        })


        $(document).ready(function() {
            send_POST();
            $('.column_search').val('');
        });
    </script>

{% endblock %}

admin_house/templates/admin_house/house_update.html
{% extends 'admin_house/house_create.html' %}
{% block title %}Редагування будинку{% endblock %}
{% block breadcrumb %}
    <ul class="breadcrumb">
        <li><a href="{% url 'statistic' %}"><i class="fa fa-home"></i>Головна</a></li>
        <li><a href="{% url 'house_list' %}">Будинки</a></li>
        <li><a href="{% url 'house_view' house.pk %}">{{ house.name }}</a></li>
        <li class="active">Редагування</li>
</ul>
{% endblock %}
{% block header_text %}
    {{house.name}}
{% endblock %}

admin_house/templates/admin_house/house_view.html
{% extends 'layout/admin_panel.html' %}
{% load static %}
{% block title %}Будинок{% endblock %}
{% block breadcrumb %}
        <ul class="breadcrumb">
        <li><a href="{% url 'statistic' %}"><i class="fa fa-home"></i>Головна</a></li>
        <li><a href="{% url 'house_list' %}">Будинки</a></li>
        <li class="active">{{house.name}}</li>
</ul>
{% endblock %}
{% block header_text %}
    {{house.name}}
{% endblock %}
{% block content %}


<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title"></h3>
        <div class="box-tools">
            <a href="{% url 'house_update' house.pk %}" class="btn btn-primary btn-sm">
                <span class="hidden-xs">Редагувати будинок</span><i class="fa fa-pencil visible-xs" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-xs-12 col-lg-4">
                <table class="table table-bordered table-striped table-view">
                    <tbody>
                        <tr>
                            <td>Назва</td>
                            <td>{{house.name}}</td>
                        </tr>
                        <tr>
                            <td>Адреса</td>
                            <td>{{house.address}}</td>
                        </tr>
                        <tr>
                            <td>Секцій</td>
                            <td>{{house.section_set.count}}</td>
                        </tr>
                        <tr>
                            <td>Поверхів</td>
                            <td>{{house.floor_set.count}}</td>
                        </tr>
                                                <tr>
                            <td>Користувачі</td>
                                                    <td>
                                                    {% if house.houseuser_set.all%}
                                                        {% for house_user in house.houseuser_set.all %}
                                                        <p class="no-margin"><strong>{{house_user.user.role}}:</strong>
                                                            <a href="{% url 'view_user' house_user.user.pk %}">
                                                                {{house_user.user}}</a>
                                                        </p>
                                                        {% endfor %}
                                                    {% else %}
                                                        Не призначено
                                                    {% endif %}
                                                    </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-xs-12 col-lg-8">
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <img src="{% if house.image1 %}
                                        {{house.image1.url}}
                                        {% else %}
                                        {% static 'admin_panel/dist/img/placeholder_522x350.jpeg' %}
                                        {% endif %}
                                        "
                             class="img-responsive largeImg margin-bottom-30" alt="">
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <img src="{% if house.image2 %}
                                        {{house.image2.url}}
                                        {% else %}
                                        {% static 'admin_panel/dist/img/placeholder_248x160.jpeg' %}
                                        {% endif %}
                                        "
                             class="img-responsive smallImg margin-bottom-30" alt="">
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <img src="{% if house.image3 %}
                                        {{house.image3.url}}
                                        {% else %}
                                        {% static 'admin_panel/dist/img/placeholder_248x160.jpeg' %}
                                        {% endif %}
                                        "
                             class="img-responsive smallImg margin-bottom-30" alt="">

                    </div>
                    <div class="col-xs-6 col-md-3">
                        <img src="{% if house.image4 %}
                                        {{house.image4.url}}
                                        {% else %}
                                        {% static 'admin_panel/dist/img/placeholder_248x160.jpeg' %}
                                        {% endif %}
                                        "
                             class="img-responsive smallImg margin-bottom-30" alt="">
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <img src="{% if house.image5 %}
                                        {{house.image5.url}}
                                        {% else %}
                                        {% static 'admin_panel/dist/img/placeholder_248x160.jpeg' %}
                                        {% endif %}
                                        "
                             class="img-responsive smallImg margin-bottom-30" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
    <script>
        $('#nav_house').attr('class', 'active')
    </script>
{% endblock %}